### PR TITLE
Enable basic auth (closes #6)

### LINKED ISSUE #6: Support basic authentication
Some specific use cases require username/password rather than an AAD token

### PR DESCRIPTION
**Pull request by hongooi73**
To use basic auth, supply `user` and `pwd` to `kusto_database_endpoint` and set `.query_token` to FALSE:

```r
kusto_database_endpoint(server="server", database="db", user="myname", pwd="mypasswd",
    .query_token=FALSE)
```

### CODE REVIEW

**Comment by hongooi73** [comment]
Also fixed the examples in the documentation to include "https://" in the server property.

**Comment by hongooi73** [comment]
@jicyang, can you see if this works with Aria?

**Comment by jicyang** [comment]
> @jicyang, can you see if this works with Aria?

Will try and let you know my test. Thank you!

**Comment by jicyang** [comment]
Hi, @Hong-Revo, the username & password authorization is not supported by Aria. I had a long conversation with help team for Aria query. Based on the conversation, Bearer authorization is the right way to go I think. But unfortunately, I still haven't figure out a way to construct a correct connection string.

**Comment by jicyang** [comment]
I can forward you those conversation emails if that is helpful... @Hong-Revo

**Comment by hongooi73** [comment]
@jicyang yes, please do.

**Comment by hongooi73** [comment]
We still haven't confirmed exactly what Aria does, but I don't think this PR is needed anymore.

**Pull request closed without merging**
